version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DATABASE: "secret_santa"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./init.sql:/usr/src/init.sql
    networks:
      - app-network

  backend:
    build:
      context: ./secret_santa
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "44395:8080"
      - "44394:443"
    depends_on:
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database= secret_santa;User Id=sa;Password=Password1!;TrustServerCertificate=true;
      - ASPNETCORE_URLS=https://+:443;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    networks:
      - app-network

  frontend:
    build:
      context: ./secret_santa_frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge
